### PR TITLE
Correct install issues

### PR DESCRIPTION
**Pull request by incon**

### CODE REVIEW

**Comment by incon** [comment]
Why does this package use a forked version of mpdf?

**Comment by misterspelik** [comment]
Hello @incon hope you are doing well. Thank you very much for your PR.
Can I please ask you to revert your changes in tests and I will merge your PR. (as you can see this change just duplicates the extension so file becomes exposify.pdf.pdf)

In terms of the version of mpdf, there was a bug in original version of mpdf for a long files with colors and it was fixed in the forked repo. But it was not merged for a long time so I had to publish a package and use it. 

I'll check if the original issue was fixed and if yes I'll switch to the original repo as well.

**Comment by misterspelik** [comment]
Actually I have already fixed the tests, and the composer.json file.
Thank you very much for pointing out.

Also in main branch I added compatibility with the new versions of psr/log and psr/http-message so no manual action is needed.

**Comment by misterspelik** [comment]
Closing this one due to no activity, thank you very much for pointing out the issues!

**Pull request closed without merging**
